---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: lint + test
    image: 72636c/golang:1.12
    commands:
      - ./scripts/lint-test.sh
    depends_on:
      - clone
    when:
      event:
        - pull_request
        - push

  - name: build + package
    image: 72636c/golang:1.12
    commands:
      - ./scripts/build-package.sh
    depends_on:
      - clone
    environment:
      OUTDIR: /tmp/dist
    volumes:
      - name: dist
        path: /tmp/dist
    when:
      event:
        - pull_request
        - push

  - name: publish
    image: node:10.15
    commands:
      - npx semantic-release
    depends_on:
      - build + package
    environment:
      GITHUB_TOKEN:
        from_secret: github/public_repo
      # https://github.com/npm/uid-number/issues/7
      NPM_CONFIG_UNSAFE_PERM: true
    volumes:
      - name: dist
        path: /tmp/dist
    when:
      branch:
        - master
      event:
        - push

volumes:
  - name: dist
    temp: {}

---
kind: signature
hmac: 43eeb9c363df652fc7cc29f0ff89a61970aadc937c3369481fb2f592044b9e0b
